version: "3.8"

services:
  tropical-ai-chef:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tropical-ai-chef-app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tropical-ai-chef.rule=Host(`localhost`)"
      - "traefik.http.services.tropical-ai-chef.loadbalancer.server.port=80"
    networks:
      - tropical-network

  # Optional: Add Traefik for load balancing in production
  reverse-proxy:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tropical-network
    profiles:
      - traefik

networks:
  tropical-network:
    driver: bridge

volumes:
  app-logs:
    driver: local
