// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylwpnufczodusbyhajra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsd3BudWZjem9kdXNieWhhanJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NDQwNzEsImV4cCI6MjA4ODMyMDA3MX0.94lw9SCn0aqhdBumbvfn-HsKZZFTfbA3cbu7rl6c1Og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});