// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwjiomyzwtfeabqytsop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3amlvbXl6d3RmZWFicXl0c29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjkwNTMsImV4cCI6MjA3MTkwNTA1M30.yio8R5_Ahypb8yGUnEazqv-Mq5hvuYGGOUtjOQk4G0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});